### ISSUE TITLE
putting objects on the board

### ISSUE THREAD

**Issue by augmediator** [gojko/hexgridwidget#2]
Hey gojko -

I was checking out your board - it's cool!  I'm trying to make an arena battle game where two players move six characters around on the board. I'm at the state where I'm trying to get one of my 'characters' to show up on the board on or inside of a hex - however I'm not able to append an object (in this case a .png file) to any hex.

I noticed your readme states that users can put object on top of the board, instead of appending it to the the interior of the object itself. How does one do that?

Thanks!

**Comment by gojko** [comment]
you can select any grid element using DOM selectors, eg `$('#container [hex-row=2][hex-column=3]')`. There are two ways to put things on the map. One is using CSS (eg just get that element and set the CSS background image). the other is to use DOM to position something absolutely over it. You can get the screen coordinates of any element using the jQuery data, for example:

``` javascript
$('#container [hex-row=2][hex-column=3]').data('center');
```

then place something programatically so it's centred on that point

**Comment by gojko** [comment]
just a final note - the grid elements are SVG polygons, so you can only use CSS that applies to SVG.
